## Car Prediction Neural Network

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf # Handling with Deep Learning Models

In [4]:
tensor_zero_d=tf.constant(0)
print(tensor_zero_d)
print(tensor_zero_d.ndim)

tf.Tensor(0, shape=(), dtype=int32)
0


In [33]:
tensor_one_d=tf.constant([0,1,2])
print(tensor_one_d)
print(tensor_one_d.ndim)

tf.Tensor([0 1 2], shape=(3,), dtype=int32)
1


In [34]:
tensor_two_d=tf.constant([[0,1,2],
                           [4,5,6]])
print(tensor_two_d)
print(tensor_two_d.ndim)

tf.Tensor(
[[0 1 2]
 [4 5 6]], shape=(2, 3), dtype=int32)
2


In [35]:
tensor_three_d=tf.constant([[[0,1,2],
                           [4,5,6]],
                          [[0,1,2],
                           [4,5,6]],])
print(tensor_three_d)
print(tensor_three_d.ndim)

tf.Tensor(
[[[0 1 2]
  [4 5 6]]

 [[0 1 2]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)
3


## Converting String to Tensors

In [8]:
tensor_string=tf.constant(['hello','hi'])
print(tensor_string)

tf.Tensor([b'hello' b'hi'], shape=(2,), dtype=string)


## Converting Boolean to Tensors

In [9]:
tensor_bool=tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


## Converting Numpy Array Into Tensor 

In [11]:
arr=np.array([1,2,3,4,5])
tensor_array=tf.convert_to_tensor(arr)
print(tensor_array)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)


## Eye Tensor
```Parameters: num_columns, num_rows, batch_shape```


In [19]:
eye=tf.eye(num_columns=None,num_rows=3,batch_shape=[4,])
print(eye)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(4, 3, 3), dtype=float32)


## Fill Tensor
```Parameters: dim, value, name```

In [ ]:
fill_tensor=tf.fill(
    [3,3],5
)
print(fill_tensor)

tf.Tensor(
[[5 5 5]
 [5 5 5]
 [5 5 5]], shape=(3, 3), dtype=int32)


## One Tensor
```Parameters: shape```

In [25]:
one_tensors=tf.ones([1,3,3])
print(one_tensors)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 3, 3), dtype=float32)


## Ones_Like Tensor

In [27]:
ones_like_tensor=tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


## Zero Tensors

In [28]:
zero_tensors=tf.zeros([1,3,3])
print(zero_tensors)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 3, 3), dtype=float32)


## Zeros_Like Tensors

In [32]:
zero_tensors=tf.zeros_like(fill_tensor)
print(zero_tensors)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)


## Tensor Shape

In [37]:
tensor_shape=tf.shape(tensor_three_d)
print(tensor_shape)

tf.Tensor([2 2 3], shape=(3,), dtype=int32)


## Tensor Rank

In [38]:
tensor_one_rank= tf.rank(tensor_one_d)
tensor_two_rank= tf.rank(tensor_two_d)
tensor_three_rank= tf.rank(tensor_three_d)
print(tensor_one_rank)
print(tensor_two_rank)
print(tensor_three_rank)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


## Tensor Size
```Return Total Numbers of Elements in the Tensor```

In [41]:
tensor_size=tf.size(tensor_three_d)
print(tensor_size)

tf.Tensor(12, shape=(), dtype=int32)


## Tensor Random_Normal
```This Distributes Randomely by using Normal Distribution```

In [48]:
random_normal_tensor=tf.random.normal([2,3],stddev=1.0,mean=0.0,seed=42)
print(random_normal_tensor)

tf.Tensor(
[[ 0.78145     0.791597    2.5034976 ]
 [ 0.47428164  0.83979404 -1.2243588 ]], shape=(2, 3), dtype=float32)


## Tensor Random_Uniform
```This Distributes Randomely by using Uniform Distribution```

In [52]:
random_uniform_tensor=tf.random.uniform(
    [3,3],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_uniform_tensor)

tf.Tensor(
[[43.744385  59.914673   3.7461638]
 [67.130264  24.214994  44.717228 ]
 [84.49286    7.9793096 46.64097  ]], shape=(3, 3), dtype=float32)


## Random Seed
```Generated Random Numbers will not changes``` 

In [60]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5, dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)


## Random Shuffle
```Shuffle The Data Points```

In [64]:
random_shuffle=tf.random.shuffle(
    [[1, 2], [3, 4], [5, 6], [7, 8]], seed=None, name=None
)
print(random_shuffle)
print(tensor_three_d)

tf.Tensor(
[[7 8]
 [5 6]
 [1 2]
 [3 4]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[[0 1 2]
  [4 5 6]]

 [[0 1 2]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)


## Tensor Indexing

In [83]:
#                       0,1,2,3,4,5,6
tensor_indexed=tf.constant([1,2,3,4,5,6,7])
print(tensor_indexed[0:6+1])

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


In [90]:
tensor_indexed[-7:-1]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [92]:
tensor_indexed[-7:-5+1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [96]:
print(tensor_indexed)
print(tensor_indexed[0:7:2])

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([1 3 5 7], shape=(4,), dtype=int32)


## 2d Array

In [99]:
td_indexed=tf.constant([[1,2,5,8,9],
                        [0,0,1,2,3],
                        [1,2,1,5,4]])

In [ ]:
# Single element
print(td_indexed[2,4])

tf.Tensor(4, shape=(), dtype=int32)


In [106]:
# Multiple elements
print(td_indexed[0,0:3])

tf.Tensor([1 2 5], shape=(3,), dtype=int32)


In [ ]:
# Multiple elements
print(td_indexed[0:2+1,2])

tf.Tensor([5 1 1], shape=(3,), dtype=int32)


In [ ]:
# Multiple elements
# : will also select the rows
print(td_indexed[:,2])

In [ ]:
# Selecting particular elements from the tensor
print(td_indexed[0:1+1,2:4])

tf.Tensor(
[[5 8]
 [1 2]], shape=(2, 2), dtype=int32)


## Math Functions

In [115]:
t_tensor=tf.constant([1,2,-3,2,-3,-3])
abs_tensor=tf.abs(t_tensor)
print(abs_tensor)

tf.Tensor([1 2 3 2 3 3], shape=(6,), dtype=int32)


## Addition

In [116]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([1,2,3,4,5])
print(tf.add(x,y))

tf.Tensor([ 2  4  6  8 10], shape=(5,), dtype=int32)


In [118]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([1])
print(tf.add(x,y))

tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)


## Substraction

In [119]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([1,2,3,4,5])
print(tf.subtract(x,y))

tf.Tensor([0 0 0 0 0], shape=(5,), dtype=int32)


In [120]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([1])
print(tf.subtract(x,y))

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


## Multiply

In [ ]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([1,2,3,4,5])
print(tf.multiply(x,y))

In [123]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([[1],[3]])
print(tf.math.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4  5]
 [ 3  6  9 12 15]], shape=(2, 5), dtype=int32)


## Division

In [121]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([1,2,3,4,5])
print(tf.divide(x,y))

tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float64)


## Maximum

In [125]:
x=tf.constant([1,2,3,8,5])
y=tf.constant([1,2,7,4,10])
print(tf.math.maximum(x,y))

tf.Tensor([ 1  2  7  8 10], shape=(5,), dtype=int32)


## Minimum

In [126]:
x=tf.constant([1,2,3,8,5])
y=tf.constant([1,2,7,4,10])
print(tf.math.minimum(x,y))

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


## Argmax & Argmin

In [128]:
A=tf.constant([1,2,3,8,5])
tf.math.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [129]:
A=tf.constant([1,2,3,8,5])
tf.math.argmin(A)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

## Reduce Tensor
```Will Reduce the metrics into one Value```

In [131]:
x=tf.constant([1,2,3,4,5])
reduce_tensor=tf.math.reduce_max(x)
print(reduce_tensor)

tf.Tensor(5, shape=(), dtype=int32)


In [134]:
# Sum of the Tensor
x=tf.constant([1,2,3,4,5])
reduce_tensor=tf.math.reduce_sum(x,keepdims=False)
reduce_tensor1=tf.math.reduce_sum(x,keepdims=True)
print(reduce_tensor)
print(reduce_tensor1)


tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor([15], shape=(1,), dtype=int32)


In [136]:
# sigmoid function
x=tf.constant([0.0,-1.2,0.9,1.5,50.0])
tensor_sigmoid=tf.math.sigmoid(x)
print(tensor_sigmoid)

tf.Tensor([0.5        0.2314752  0.7109495  0.81757444 1.        ], shape=(5,), dtype=float32)


## Linear ALgebra