#### Numpy

In [3]:
import numpy as np

# create 1d Array
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
arr.ndim

[1 2 3 4 5]
(5,)


1

In [4]:
## 2D Array
import numpy as np
arr1 = np.array([[1,2,3,4,5],
                [1,2,3,4,5]])

print(arr1.shape)

(2, 5)


In [5]:
## Create Array using IN-BUILD Array
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [6]:
arrones = np.ones((3,3), dtype="int")
print(arrones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
#identity matrix
# np.eye(3, dtype="int")
arr = np.eye(3)
arr.shape
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
ar = np.array([[[1,2,3,4,5],
               [1,2,3,4,5],
               [1,2,3,4,5]]])

print(f"Array : {ar}")
print(f"The Shape of Array is : {ar.shape}")
print(f"The Dimension of the Array is : {ar.ndim}")
print(f"The size of Array : {ar.size}")
print(f"Data Type: {ar.dtype}")


Array : [[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]
The Shape of Array is : (1, 3, 5)
The Dimension of the Array is : 3
The size of Array : 15
Data Type: int64


#### Numpy Vectorized Opearation

In [9]:
#Vector Opearation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

print(f"Addition: {arr1 + arr2}")
print(f"Substraction: {arr1 - arr2}")
print(f"Multiplication: {arr1 * arr2}")
print(f"Division: {arr1 * arr2}")

Addition: [ 2  4  6  8 10]
Substraction: [0 0 0 0 0]
Multiplication: [ 1  4  9 16 25]
Division: [ 1  4  9 16 25]


In [10]:
#Universal Function
arr = np.array([2,4,5,7,8])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))

[1.41421356 2.         2.23606798 2.64575131 2.82842712]
[   7.3890561    54.59815003  148.4131591  1096.63315843 2980.95798704]
[0.69314718 1.38629436 1.60943791 1.94591015 2.07944154]
[ 0.90929743 -0.7568025  -0.95892427  0.6569866   0.98935825]


In [16]:
# Array Slicing & Indexing
#                0 1 2
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
print(arr[0][1])
print(arr[1][1])
print(arr[2][0])

2
6
9


In [19]:
# slicing
print(arr)
arr[1:3, 1:3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 6,  7],
       [10, 11]])

In [23]:
#Modify The Array Element
arr[1:3, 1:3] = 110
print(arr)

[[110   2   3   4]
 [  5 110 110   8]
 [  9 110 110  12]]


In [24]:
data = np.array([1,2,3,4,5,6,7,8,9])

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)

std = np.std(data)
print(std)

var = np.var(data)
print(var)


5.0
5.0
2.581988897471611
6.666666666666667


In [29]:
data = np.array([1,2,3,4,5,6,7,8,9])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])